Repository rust-lang/rust-playground, pull requests merged in 2018-04, with the labels that each got.

#291 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  top-crates/src/main.rs
  ui/src/gist.rs
Labels: bug, maintenance

#292 Test updates
  tests/Gemfile
  tests/Gemfile.lock
  tests/spec/features/tools_spec.rb
  tests/spec/spec_helper.rb
Labels: maintenance

#293 Frontend updates
  ui/frontend/package.json
  ui/frontend/webpack.config.js
  ui/frontend/yarn.lock
Labels: maintenance

#298 Update crates
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  top-crates/Cargo.lock
Labels: maintenance

#297 Add dotenv support
  README.md
  ui/Cargo.lock
  ui/Cargo.toml
  ui/README.md
  ui/src/main.rs
Labels: enhancement

#296 Update Docker login procedure to newest recommended by Travis
  .travis/build-containers.sh
Labels: maintenance

#305 Restore scrolling of the help page
  ui/frontend/index.scss
Labels: bug

#306 JavaScript libraries maintenance
  ui/frontend/SegmentedButton.tsx
  ui/frontend/augmentations/react.d.ts
  ui/frontend/package.json
  ui/frontend/uss-router/Link.tsx
  ui/frontend/yarn.lock
Labels: maintenance

#310 Make the linter run on Windows
  ui/frontend/package.json
Labels: maintenance

#315 Enhance outbound links
  ui/frontend/highlighting.ts
  ui/frontend/index.tsx
Labels: enhancement
