Repository rust-lang/rust-playground, pull requests merged in 2018-06, with the labels that each got.

#341 Disable auto-correct on Simple Editor
  ui/frontend/Editor.tsx
Labels: enhancement

#342 Match error and warning text only when they start the line of output
  ui/frontend/highlighting.ts
Labels: bug

#343 Use fixed crate versions across stable, beta, and nightly
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  top-crates/Cargo.lock
  top-crates/src/main.rs
Labels: bug, maintenance

#344 Add the current crate version when autocompleting the crate
  ui/frontend/AdvancedEditor.tsx
Labels: enhancement

#345 Upgrade test semver dependencies
  tests/Gemfile.lock
Labels: maintenance

#348 Load the ACE searchbox component
  ui/frontend/advanced-editor.ts
Labels: bug

#350 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  top-crates/Cargo.lock
  ui/Cargo.lock
  ui/Cargo.toml
Labels: maintenance

#351 Allow selecting the Rust edition
  compiler/base/modify-cargo-toml/src/main.rs
  tests/spec/features/editions_spec.rb
  tests/spec/features/sharing_with_others_spec.rb
  tests/spec/features/url_parameters_spec.rb
  tests/spec/support/playground_actions.rb
  ui/frontend/AdvancedOptionsMenu.tsx
  ui/frontend/ConfigElement.tsx
  ui/frontend/Header.tsx
  ui/frontend/Icon.tsx
  ui/frontend/Output.tsx
  ui/frontend/Router.tsx
  ui/frontend/actions.ts
  ui/frontend/index.scss
  ui/frontend/reducers/configuration.ts
  ui/frontend/reducers/output/gist.ts
  ui/frontend/selectors/index.ts
  ui/frontend/types.ts
  ui/src/main.rs
  ui/src/sandbox.rs
Labels: enhancement
