Repository rust-lang/rust-playground, pull requests merged in 2018-09, with the labels that each got.

#398 Show versions of tools.
  ui/frontend/ToolsMenu.tsx
  ui/frontend/actions.ts
  ui/frontend/index.scss
  ui/frontend/reducers/versions.ts
  ui/frontend/selectors/index.ts
  ui/src/main.rs
  ui/src/sandbox.rs
Labels: enhancement

#401 Compiler container refresh
  compiler/base/Cargo.toml
  compiler/base/Dockerfile
  compiler/base/crate-information.json
  top-crates/Cargo.lock
Labels: maintenance

#402 Enable -Z asm-comments on nightly
  ui/src/sandbox.rs
Labels: enhancement

#403 The Cargo "edition" feature is now stable
  compiler/base/modify-cargo-toml/Cargo.lock
  compiler/base/modify-cargo-toml/Cargo.toml
  compiler/base/modify-cargo-toml/src/main.rs
Labels: maintenance

#412 Support Rust 2018 in the beta channel
  tests/spec/features/editions_spec.rb
  tests/spec/features/tools_spec.rb
  ui/frontend/AdvancedOptionsMenu.tsx
  ui/frontend/actions.ts
  ui/frontend/reducers/configuration.ts
  ui/frontend/selectors/index.ts
Labels: enhancement, maintenance
