Repository rust-lang/rust-playground, pull requests merged in 2019-01, with the labels that each got.

#455 Update crates available in the playground
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
Labels: maintenance

#460 Build crates with support for Miri
  compiler/base/Cargo.toml
  compiler/base/Dockerfile
  compiler/base/crate-information.json
  compiler/build.sh
  compiler/clippy/Dockerfile
  compiler/miri/Dockerfile
  compiler/rustfmt/Dockerfile
  top-crates/crate-modifications.toml
Labels: enhancement, maintenance

#461 Support edition and crate type when running Clippy
  tests/Gemfile
  tests/Gemfile.lock
  tests/spec/features/tools_spec.rb
  tests/spec/features/url_parameters_spec.rb
  ui/frontend/actions.ts
  ui/frontend/selectors/index.ts
  ui/src/main.rs
  ui/src/sandbox.rs
Labels: bug, maintenance
