Repository rust-lang/rust-playground, pull requests merged in 2020-01, with the labels that each got.

#557 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
Labels: maintenance

#558 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  top-crates/crate-modifications.toml
Labels: maintenance

#561 Automatically ignore crates for other platforms
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  top-crates/crate-modifications.toml
  top-crates/src/main.rs
Labels: enhancement, maintenance

#562 Allow selecting the menu button's text
  ui/frontend/index.scss
Labels: enhancement

#564 Add support for async main function
  ui/frontend/selectors/index.spec.ts
  ui/frontend/selectors/index.ts
Labels: enhancement

#556 Avoid using the root user during compiler execution
  compiler/base/Cargo.toml
  compiler/base/Dockerfile
  compiler/base/crate-information.json
  compiler/base/entrypoint.sh
  compiler/base/modify-cargo-toml/Cargo.lock
  compiler/clippy/Dockerfile
  compiler/miri/Dockerfile
  compiler/rustfmt/Dockerfile
  ui/Cargo.lock
  ui/Cargo.toml
  ui/src/gist.rs
  ui/src/sandbox.rs
Labels: maintenance

#565 Test maintenance
  tests/Gemfile.lock
  tests/spec/features/highlighting_error_output_spec.rb
Labels: maintenance

#566 Proactively create the output directory and make it world-writable
  ui/src/sandbox.rs
Labels: bug

#567 Make the input file world-writable as well
  ui/src/sandbox.rs
Labels: bug
