Repository rust-lang/rust-playground, pull requests merged in 2021-04, with the labels that each got.

#696 Increase default memory limits
  tests/Gemfile
  tests/Gemfile.lock
  tests/spec/features/highlighting_error_output_spec.rb
  ui/src/sandbox.rs
Labels: CI: approved

#697 Remove "Open an issue" link
  tests/spec/features/sharing_with_others_spec.rb
  ui/frontend/Output/Gist.tsx
  ui/frontend/selectors/index.ts
Labels: CI: approved, maintenance

#702 Prevent expanding the window size when adjusting the split
  ui/frontend/Playground.module.css
  ui/frontend/Playground.tsx
Labels: CI: approved, bug

#703 Adjust positioning of the popper arrow so it is centered
  ui/frontend/PopButton.module.css
Labels: CI: approved, bug

#709 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  ui/Cargo.lock
Labels: CI: approved, maintenance
