Repository rust-lang/rust-playground, pull requests merged in 2021-03, with the labels that each got.

#687 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  tests/Gemfile.lock
  tests/spec/requests/caching_spec.rb
  ui/frontend/Output/Gist.tsx
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: maintenance

#690 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  top-crates/Cargo.lock
  ui/Cargo.lock
Labels: maintenance

#691 Require approval before starting a CI run
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  ci/workflows.yml
Labels: CI: approved, maintenance

#692 Still run CI for master branch pushes
  .github/workflows/ci.yml
  ci/workflows.yml
Labels: CI: approved, maintenance

#683 Add support for -Zunpretty=hir
  tests/spec/features/compilation_targets_spec.rb
  ui/frontend/BuildMenu.tsx
  ui/frontend/Output.tsx
  ui/frontend/actions.ts
  ui/frontend/reducers/output/hir.ts
  ui/frontend/reducers/output/index.ts
  ui/frontend/reducers/output/meta.ts
  ui/frontend/selectors/index.ts
  ui/frontend/types.ts
  ui/src/main.rs
  ui/src/sandbox.rs
Labels: CI: approved
