Repository rust-lang/rust-playground, pull requests merged in 2021-05, with the labels that each got.

#711 Use `--unpretty=expanded` instead of `--pretty`
  ui/src/sandbox.rs
Labels: CI: approved

#714 Introduce some metrics about endpoints and their arguments/outcomes
  deployment/update.sh
  tests/Gemfile.lock
  tests/spec/features/compilation_targets_spec.rb
  ui/Cargo.lock
  ui/Cargo.toml
  ui/README.md
  ui/src/main.rs
  ui/src/sandbox.rs
Labels: CI: approved, maintenance

#717 Add support for Rust 2021
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  compiler/base/modify-cargo-toml/src/main.rs
  tests/Gemfile.lock
  tests/spec/features/editions_spec.rb
  tests/spec/features/sharing_with_others_spec.rb
  tests/spec/features/url_parameters_spec.rb
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  top-crates/src/main.rs
  ui/Cargo.lock
  ui/frontend/AdvancedEditor.tsx
  ui/frontend/AdvancedOptionsMenu.tsx
  ui/frontend/ConfigElement.tsx
  ui/frontend/actions.ts
  ui/frontend/selectors/index.ts
  ui/frontend/types.ts
  ui/src/main.rs
  ui/src/sandbox.rs
Labels: CI: approved, enhancement, maintenance

#674 Update README.md
  README.md
Labels: CI: approved

#721 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  top-crates/Cargo.lock
  ui/Cargo.lock
Labels: CI: approved, maintenance
