Repository rust-lang/rust-playground, pull requests merged in 2021-09, with the labels that each got.

#738 Maintenance
  ci/Gemfile
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  tests/Gemfile.lock
  tests/spec/features/highlighting_error_output_spec.rb
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  top-crates/src/lib.rs
  ui/Cargo.lock
  ui/Cargo.toml
Labels: maintenance, CI: approved

#743 Remove special case for cargo "edition2021" feature
  compiler/base/modify-cargo-toml/src/main.rs
  ui/src/sandbox.rs
Labels: CI: approved

#744 Don't change Ace's gutter size on scroll
  ui/frontend/AdvancedEditor.tsx
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: bug, maintenance, CI: approved

#746 Track RSpec failures to easily retry them when debugging
  tests/spec/features/compilation_targets_spec.rb
  tests/spec/spec_helper.rb
Labels: maintenance, CI: approved
