Repository rust-lang/rust-playground, pull requests merged in 2023-09, with the labels that each got.

#964 Unconditionally terminate the WebSocket connection after some time
  compiler/base/orchestrator/src/coordinator.rs
  ui/Cargo.toml
  ui/src/server_axum/websocket.rs
Labels: maintenance

#965 Use Capybara waiting for URL tests
  tests/spec/support/matchers/be_at_url.rb
Labels: maintenance

#966 Upgrade JS dependencies
  ui/frontend/.babelrc
  ui/frontend/.prettierrc.json
  ui/frontend/Output/Gist.module.css
  ui/frontend/PopButton.module.css
  ui/frontend/SegmentedButton.module.css
  ui/frontend/index.tsx
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: maintenance, javascript

#969 Route evaluate requests through the orchestrator
  .github/workflows/ci.yml
  ci/workflows.yml
  tests/spec/features/navigation_spec.rb
  ui/src/main.rs
  ui/src/server_axum.rs
  ui/src/server_axum/websocket.rs
Labels: enhancement, maintenance

#971 Create each channel's container lazily
  compiler/base/orchestrator/src/coordinator.rs
  ui/src/main.rs
  ui/src/server_axum.rs
  ui/src/server_axum/websocket.rs
Labels: maintenance

#973 Kill the tasks using the Coordinator before shutting it down
  ui/src/server_axum/websocket.rs
Labels: maintenance

#975 Replace the CancellationToken with a new one when idling
  compiler/base/orchestrator/src/coordinator.rs
Labels: bug

#976 Test that coordinator is still usable after idling
  compiler/base/orchestrator/src/coordinator.rs
Labels: maintenance

#977 Track metrics when executing via the WebSocket
  ui/src/metrics.rs
  ui/src/server_axum.rs
  ui/src/server_axum/websocket.rs
Labels: maintenance

#972 Prevent output pane text from being copied as HTML
  ui/frontend/Output/SimplePane.tsx
Labels: CI: approved
