Repository rust-lang/rust-playground, pull requests merged in 2023-01, with the labels that each got.

#880 Maintenance
  tests/Gemfile.lock
  ui/frontend/AdvancedOptionsMenu.tsx
  ui/frontend/ButtonMenuItem.tsx
  ui/frontend/ChannelMenu.tsx
  ui/frontend/ConfigElement.module.css
  ui/frontend/ConfigElement.tsx
  ui/frontend/ConfigMenu.tsx
  ui/frontend/Header.tsx
  ui/frontend/HeaderButton.tsx
  ui/frontend/Help.tsx
  ui/frontend/MenuAside.tsx
  ui/frontend/MenuGroup.tsx
  ui/frontend/MenuItem.tsx
  ui/frontend/ModeMenu.tsx
  ui/frontend/Notifications.tsx
  ui/frontend/Output/Gist.tsx
  ui/frontend/Output/OutputPrism.tsx
  ui/frontend/Output/Section.tsx
  ui/frontend/Output/SimplePane.tsx
  ui/frontend/PopButton.module.css
  ui/frontend/Router.tsx
  ui/frontend/SegmentedButton.tsx
  ui/frontend/SelectOne.tsx
  ui/frontend/editor/AceEditor.tsx
  ui/frontend/editor/Editor.tsx
  ui/frontend/index.tsx
  ui/frontend/package.json
  ui/frontend/uss-router/Link.tsx
  ui/frontend/uss-router/Router.tsx
  ui/frontend/uss-router/index.ts
  ui/frontend/yarn.lock
Labels: maintenance

#882 Add a security policy
  SECURITY.md
Labels: maintenance

#888 Rollback react-monaco-editor to reduce flicker
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: bug

#873 Update address bar after saving Gist
  tests/spec/features/navigation_spec.rb
  tests/spec/features/sharing_with_others_spec.rb
  tests/spec/support/matchers/be_at_url.rb
  ui/frontend/Output/Gist.tsx
  ui/frontend/Router.tsx
  ui/frontend/selectors/index.ts
Labels: enhancement, CI: approved
