Repository rust-lang/rust-playground, pull requests merged in 2023-05, with the labels that each got.

#927 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  tests/Gemfile.lock
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  top-crates/src/main.rs
  ui/Cargo.lock
  ui/Cargo.toml
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: maintenance

#925 Add a security notice to commonly inspected files
  compiler/base/Dockerfile
  compiler/base/attach_notice.sh
  compiler/base/security_notice.txt
  tests/spec/features/security_spec.rb
Labels: CI: approved

#912 Wait for a WebSocket connection to close before reconnecting
  ui/frontend/reducers/websocket.ts
  ui/frontend/websocketMiddleware.ts
  ui/src/server_axum/websocket.rs
Labels: bug

#931 Remove deprecated actions-rs usage
  .github/workflows/ci.yml
  ci/workflows.yml
Labels: maintenance
