Repository rust-lang/rust-playground, pull requests merged in 2023-02, with the labels that each got.

#890 Add metrics for number of active sessions and sessions' durations
  tests/spec/features/tools_spec.rb
  ui/Cargo.lock
  ui/Cargo.toml
  ui/frontend/declarations.d.ts
  ui/frontend/index.tsx
  ui/frontend/websocket.ts
  ui/src/metrics.rs
  ui/src/server_axum.rs
Labels: CI: approved

#891 Report WebSocket errors that occur after construction
  ui/frontend/websocket.ts
Labels: enhancement

#895 Namespace playground WebSocket metrics
  ui/src/metrics.rs
Labels: maintenance

#897 Enable WebSocket connection for everyone
  ui/frontend/index.tsx
Labels: maintenance

#896 update error-index hyperlinks
  tests/spec/features/highlighting_error_output_spec.rb
  ui/frontend/highlighting.ts
Labels: CI: approved

#898 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  compiler/base/modify-cargo-toml/Cargo.toml
  tests/Gemfile.lock
  tests/spec/features/assistance_spec.rb
  tests/spec/spec_helper.rb
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  top-crates/src/main.rs
  ui/Cargo.lock
  ui/Cargo.toml
  ui/frontend/PopButton.module.css
  ui/frontend/package.json
  ui/frontend/yarn.lock
  ui/src/server_axum.rs
Labels: maintenance

#901 Maintenance
  .github/workflows/ci.yml
  ci/workflows.yml
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  tests/Gemfile.lock
  top-crates/Cargo.lock
  ui/Cargo.lock
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: maintenance
