Repository rust-lang/rust-playground, pull requests merged in 2023-06, with the labels that each got.

#934 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  ui/Cargo.lock
  ui/Cargo.toml
  ui/frontend/highlighting.ts
  ui/src/sandbox.rs
Labels: maintenance

#939 Upgrade Docker versions in CI
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  ci/workflows.yml
  compiler/base/Cargo.toml
  compiler/base/Dockerfile
  compiler/base/crate-information.json
Labels: maintenance

#914 Allow compiling to assembly and friends in the orchestrated Docker container
  .github/workflows/ci.yml
  ci/workflows.yml
  compiler/base/.dockerignore
  compiler/base/Dockerfile
  compiler/base/asm-cleanup/.gitignore
  compiler/base/asm-cleanup/Cargo.toml
  compiler/base/asm-cleanup/src/lib.rs
  compiler/base/cargo-wasm
  compiler/base/entrypoint.sh
  compiler/base/modify-cargo-toml/src/lib.rs
  compiler/base/modify-cargo-toml/src/main.rs
  compiler/base/orchestrator/.gitignore
  compiler/base/orchestrator/Cargo.lock
  compiler/base/orchestrator/Cargo.toml
  compiler/base/orchestrator/src/bin/worker.rs
  compiler/base/orchestrator/src/coordinator.rs
  compiler/base/orchestrator/src/lib.rs
  compiler/base/orchestrator/src/message.rs
  compiler/base/orchestrator/src/worker.rs
  tests/spec/features/sharing_with_others_spec.rb
  ui/Cargo.lock
  ui/Cargo.toml
  ui/src/main.rs
  ui/src/metrics.rs
  ui/src/sandbox.rs
  ui/src/server_axum.rs
Labels: CI: approved

#940 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  top-crates/Cargo.lock
  top-crates/Cargo.toml
  ui/Cargo.lock
  ui/Cargo.toml
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: maintenance

#942 Downgrade to Ace 1.22.1
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: bug, javascript

#943 Upgrade to Ace 1.23.1
  ui/frontend/package.json
  ui/frontend/webpack.config.js
  ui/frontend/yarn.lock
Labels: maintenance
