Repository rust-lang/rust-playground, pull requests merged in 2025-03, with the labels that each got.

#1074 Allow user to specify aliasing model for Miri
  compiler/base/cargo-miri-playground
  compiler/base/orchestrator/src/coordinator.rs
  compiler/build.sh
  compiler/fetch.sh
  tests/spec/features/backtrace_spec.rb
  tests/spec/features/tools_spec.rb
  tests/spec/spec_helper.rb
  ui/frontend/.prettierignore
  ui/frontend/AdvancedOptionsMenu.tsx
  ui/frontend/ConfigElement.tsx
  ui/frontend/reducers/configuration.ts
  ui/frontend/reducers/output/miri.ts
  ui/frontend/selectors/index.ts
  ui/frontend/types.ts
  ui/src/metrics.rs
  ui/src/public_http_api.rs
  ui/src/server_axum.rs
Labels: CI: approved

#1143 Run tests with Miri
  compiler/base/Dockerfile
  compiler/base/orchestrator/src/coordinator.rs
  ui/frontend/ToolsMenu.tsx
  ui/frontend/reducers/output/miri.ts
  ui/frontend/selectors/index.ts
  ui/src/metrics.rs
  ui/src/public_http_api.rs
  ui/src/server_axum.rs
Labels: enhancement

#1145 Maintenance
  compiler/base/Cargo.toml
  compiler/base/crate-information.json
  compiler/base/modify-cargo-toml/Cargo.lock
  compiler/base/orchestrator/Cargo.lock
  compiler/base/orchestrator/Cargo.toml
  tests/Gemfile.lock
  top-crates/Cargo.lock
  ui/Cargo.lock
  ui/Cargo.toml
Labels: maintenance
